# Generated by Django 6.0.1 on 2026-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scores', models.JSONField(default=dict)),
                ('upper_bonus', models.BooleanField(default=False)),
                ('yahtzee_bonus_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_player_index', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=1)),
                ('dice', models.JSONField(default=list)),
                ('rolls_left', models.IntegerField(default=3)),
                ('kept_dice', models.JSONField(default=list)),
                ('available_categories', models.JSONField(default=dict)),
                ('players', models.ManyToManyField(related_name='games', to='yahtzee.player')),
            ],
        ),
    ]
